function baseStruct = createStage()
    % createStage: defines and creates the base structure of the experiment
    % stages

    % base struct
    baseStruct = struct( ...
        'type',           '', ...
        'trialNr',        nan, ...
        'desMatNr',       nan, ...
        'taskID',         nan, ...
        'runNr',          nan, ...
        'duration',       nan, ...
        'jitter',         nan, ...
        'nextStageAt',    nan, ...
        'onSet',          nan, ...
        'eventNext',      '', ...
        'responseInvert', nan, ...
        'daytime',        nan, ...
        'stageData',      struct([]), ...
        'customEvents',   struct( ...
            'handles',       nan, ...
            'arguments',    {} ...
            ) ...
        ); 
end
