function colorRGB = colorParser(colorName)
    % colorParser: parses the string input to a RGB vector output
    %
    % SYNTAX:   colorRGB = tools.colorParser(colorName)
    %
    % INPUTS:
    %           colorName       name of the color as a charactor vector
    %
    % OUTPUTS:
    %           colorRGB        RGB vector of the color
    %
    % EXAMPLE:
    %           white = tools.colorParser('white');
    %           white is then [255, 255, 255]
    %

    % implementation of the known colors
    DEFINEDCOLORS = struct('black',       [0  , 0  , 0  ], ...
                           'white',       [255, 255, 255], ...
                           'grey',        [128, 128, 128], ...
                           'red',         [255, 0  , 0  ], ...
                           'green',       [0  , 255, 0  ], ...
                           'light_green', [0  , 181, 0  ], ...
                           'blue',        [0  , 0  , 255], ...
                           'yellow',      [255, 255, 0  ], ...
                           'orange',      [255, 128, 0  ], ...
                           'cyan',        [0  , 255, 255], ...
                           'mangenta',    [255, 0  , 255]);

    % check if color is already knwon
    assert(ischar(colorName) && isfield(DEFINEDCOLORS, colorName), ...
        ['tools:colorPars:' colorName], ...
        [colorName ': Please add the color or chose a color of these: black, ' ...
        'white, grey, red, green, blue, yellow, cyan, mangenta']);
    colorRGB = DEFINEDCOLORS.(colorName);
end
