function resetFontSize(experimentInfo)

    assert(strcmp(experimentInfo.expToolbox, 'psychtoolbox'), ...
        'tools:psychtoolbox:initialize', ...
        'Wrong toolbox is specified! This function just runs with "psychtoolbox"');

    Screen('TextSize', ...
        experimentInfo.windowIdx, ...
        experimentInfo.defaultParam.FONTSIZE ...
        );
end